import "./globals.css";

import { Inter } from "next/font/google";

import LeftColumn from "./left-column";
import RightColumn from "./right-column";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} mx-auto flex min-h-screen flex-col items-start justify-start p-32`}
      >
        <div className="mx-auto flex gap-20">
          <div className="flex basis-3/12 flex-col gap-8">
            <LeftColumn />
          </div>
          <div className="flex basis-5/12 flex-col gap-8">{children}</div>
          <div className="flex basis-3/12 flex-col">
            <RightColumn />
          </div>
        </div>
      </body>
    </html>
  );
}
